# Generated by Django 2.1.3 on 2018-12-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='average_positivity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
