# Generated by Django 2.1.3 on 2018-12-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0004_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='sentiment_polarity',
        ),
    ]
