# Generated by Django 2.1.3 on 2018-12-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0005_remove_tweet_sentiment_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment_polarity',
            field=models.CharField(default='neutral', max_length=100),
        ),
    ]
