# Generated by Django 2.1.4 on 2018-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0006_tweet_sentiment_polarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(default='', max_length=100000)),
                ('topic_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TweetTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(default=0)),
                ('topic_coverage', models.FloatField(default=0.0)),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='topics',
            field=models.CharField(default='unknown', max_length=100000),
        ),
    ]
