# Generated by Django 2.1.3 on 2018-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0006_tweet_sentiment_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='topics',
            field=models.CharField(default='unknown', max_length=100000),
        ),
    ]
