# Generated by Django 2.1.3 on 2018-12-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0008_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(default='', max_length=100000)),
                ('topic_id', models.IntegerField(default=0)),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
