# Generated by Django 2.1.3 on 2018-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0009_tweettopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweettopic',
            name='topic_coverage',
            field=models.FloatField(default=0.0),
        ),
    ]
