# Generated by Django 2.1.3 on 2018-12-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0010_tweettopic_topic_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweettopic',
            name='topics',
        ),
    ]
